# Generated by Django 5.0.4 on 2024-06-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='imagem',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
